### ISSUE TITLE
Round fiat values to fewer significant figures

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq-core#101]
As posted by @marco4444 in proposals bisq-network/proposals#17

In order to avoid that bisq-trades can be assigned to a person via time/amount analyses (on the fiat side), it is recommended to trade with full euro amounts (0 cents), as there are then on average 39 times as many transfers of exactly the same amount on the same day in the entire currency area (compared to the average of the frequencies of the other 99 possibilities .xy).
With the current crooked amounts, it is only a question of time when many of them can be assigned to a person after the fact, since the complete history of the amounts/times is public. The smaller a currency area is, the more important this is, since the same amounts occur less frequently on the same day than for dollars and euros. Unfavorable cents such as.74 and.93 are even 390 times less common than rounded amounts and there is a high risk to be the only person in the currency area using the same amount on the same day.

**Comment by sqrrm** [comment]
I think this is in line with the Bisq philosophy and would make sense to implement.

Since each fiat currency is different they might need different schemes. We can start by rounding to nearest full fiat unit and allow for that functionality to be overridden. I can't see if there would be any issues with the trade process here, but I assume it would work just like now but with fewer digits.

**Comment by ManfredKarrer** [comment]
Implemented with PR: https://github.com/bisq-network/bisq-core/pull/146
