### ISSUE TITLE
payment methods

### ISSUE THREAD

**Issue by fst168** [bisq-network/bisq-core#104]
I investigated the Amazon visa card potential as a payment method. Here are the findings:
 1. extremely easy and anonymous for first-time/beginner buyers
 2. Cards purchased on-line
 3. Cards available in $50. and $100. amounts
 4. Seller would have to have full amount in escrow,  no potential for charge-back, no risk to buyer 
 5. Cards would be sent by mail from buyer to seller, clearly a downside, but no bank is involved on either        side of transaction.
 6. These are smaller transactions but could entice beginner buyers who don't understand satoshi's and make available some "Easy Buy" option $100 or $500.00 in btc at market price.
 7. market price at the time offer is accepted
 8. the purchase fee for the cards is $5.95 per $100.00, so $30.00 fee per $500.00, which sounds high but it's paying for ease and anonymous buying
9. I'm not sure where bisq gets it's tx fees, so don't know where in the trade that comes from
10. From a seller perspective, if I want to sell small amounts of btc $500. or $1,000. here and there, it's not easy if I don't want weird payments arriving in my bank.
 11. This system avoids kyc for both buyer/seller, with the exception of a physical address to receive the cards.
12. I don't see this method different than buying something on ebay, instead of the seller knowing an address, the buyer would know the address, (remedied w a PO box if it works).    
13. Maybe a way that after the cards arrived and are checked the btc is sent either directly to bisq to relay, or an address is provided by buyer at time of purchase. (?)
14. These gift cards are only available in the US
15. waiting for snail mail is no different than waiting for coinbase to process.
16. There are more and more on-ramps to buy, but fewer anonymous off-ramps for sellers without lots of invasive kyc.
17. These are my initial findings and will be a guinea pig to provide $500. in btc to hold in escrow to see if it works
18.Clearly this is not a system for whale buyers/sellers, but they don't need an "Easy Buy/Sell" button!
19. I suggest this be separate from the current offers page, a UI so simple my mom could buy a small amount of btc
20. https://www.amazon.com/Visa-Gift-Card-plus-Purchase/dp/B01MSBQB1P/ref=pd_rhf_ee_p_img_1?_encoding=UTF8&psc=1&refRID=89M3AP89TMDCKC6SSGSM

(long link, not sure it will work)

**Comment by blabno** [comment]
Time to move this issue to https://github.com/bisq-network/payment-methods/issues.
