### ISSUE TITLE
remove bitcoinj dependency

### ISSUE THREAD

**Issue by piem** [bisq-network/bisq-core#105]
This will probably be a bit of a political issue, but I would really like to see bisq running without bitcoinj.

The topic was raised in [Tech Session #4](https://youtu.be/JcySykHuWIQ?t=28m15s) and it seems important to address it properly. Please let me know if there a better place to have this discussion.

The two main reasons that make it very obvious to me are:
 - code diverged from bitcoin core and is obsolete
 - makes bisq depends on a white-list of «trusted» nodes

Another view on bitcoinj that might be useful: [Petter Todd describing it as a possible attack vector](https://youtu.be/DHc81OL_hk4?t=9h12m18s) (@cbeams you were in the room if I'm not mistaken ;).

**Comment by ManfredKarrer** [comment]
It is not a political issue but a practical. First we need to find an developer who is qualified to work on bitcoin stuff and who has the resources to do that. It is not a small and easy enterprise to exchange BitcoinJ with some alternative.
So from my side there is no discussion needed but dev resources to start working on that. 
First task would be to investigate and research which alternatives are most feasible.

**Comment by ManfredKarrer** [comment]
I will close that issue as there are no plans atm to work on that concretely. But it is definitely on our agenda to check out alternatives as soon we have dev resources for that.

**Comment by piem** [comment]
Unfortunately I don't have enough time to take care of this my self at the moment. 

However, if the bug exists and needs to be addressed, I'm not sure why you would want to close it.

**Comment by ManfredKarrer** [comment]
Which bug? The main issues are the broken bloom filter, but thats basically a conceptual issue and client side bloom filter are in development.

**Comment by piem** [comment]
maybe read issue instead of bug? is there a corresponding issue on broken bloom filters? a roadmap where this task is written?

**Comment by ManfredKarrer** [comment]
There are some open bounty tasks (since 1-2 years). https://github.com/bisq-network/bisq-desktop/issues/487
Closing here does not mean we are not looking into solutions, just that this GH issue does not has any well defined task to be implemented. GH issues should be kept for concrete technical tasks and I prefer to not get it polluted like in https://github.com/bisq-network/bisq-desktop/issues/ where it would take me days to clean up all...
For pure discussions the Forum might be better. 
For concrete ideas how to fix it a proposal would be the right place.

**Comment by piem** [comment]
great, thanks! yeah, i figured here was not the best location to report this, but at least now this page leads to the right place :)

**Comment by ManfredKarrer** [comment]
Here is more: https://bisq.network/blog/privacy-in-bitsquare/
