### ISSUE TITLE
Extract bisq.asset package to its own repository

### ISSUE THREAD

**Issue by blabno** [bisq-network/bisq-core#99]
- [x] Do the extraction into blabno/bisq-assets (a repository of your own creation)
- [x] Submit a PR to bisq-network/bisq-docs updating `list-asset.adoc` accordingly
- [x] Submit a PR to bisq-network/bisq updating the `.mrconfig` and `.gitignore` files accordingly.
- [x] Submit a PR to bisq-network/bisq-core deleting the package there and requesting @cbeams  to review blabno/bisq-assets and transfer it into the bisq-network repo
- [x] (at the same time as the PR above) Grant @cbeams admin rights on blabno/bisq-assets so he can actually perform the repo transfer
- [x] @cbeams does the transfer and merge all the above PRs

**Comment by cbeams** [comment]
Thanks, @blabno. Note (for others) that we decided to do this based on the conversation at https://bisq.slack.com/archives/C1267HFD1/p1524468933000097.

**Comment by blabno** [comment]
- Assets: https://github.com/blabno/bisq-assets/pull/1
- Docs: https://github.com/bisq-network/bisq-docs/pull/42
- Bisq: https://github.com/bisq-network/bisq/pull/4
- Core: https://github.com/bisq-network/bisq-core/pull/100

**Comment by cbeams** [comment]
Closing as complete. Thanks @blabno for putting all of this together. From this point out, I'll wait for your review on incoming PRs to the new `bisq-asset` repository, and then I'll merge. After we work that way for a while, say one month and I generally don't have any follow-up comments on your reviews, then I'll grant you maintainer rights on the repo so you can just take care of everything yourself. I'll set up a role and a @bisq-network/assets-maintainers team as well.
